### ISSUE TITLE
Support for emoji domains

### ISSUE THREAD

**Issue by tedmiston** [domainr/domainr-search-box#103]
When typing emoji characters into the search box or clicking a domain with emojis in the name, Domainr seems to throw HTTP 401 and 500 errors (see "🎈" example in screenshots below).

It would be nice if it supported [emoji domains][1] as they are becoming more popular today!

<img width="1792" alt="Screen Shot 2022-08-06 at 6 06 49 PM" src="https://user-images.githubusercontent.com/366688/183267515-18a677da-2502-449d-ade6-e7cbd0a9e31c.png">

<img width="1792" alt="Screen Shot 2022-08-06 at 6 06 53 PM" src="https://user-images.githubusercontent.com/366688/183267520-79c2e1d0-833b-42b6-ade7-965d12f820a6.png">

[1]: https://en.wikipedia.org/wiki/Emoji_domain

**Comment by case** [comment]
This is fixed now. Thanks again for letting us know about it, @tedmiston!
