### ISSUE TITLE
Be able to trigger an update manually

### ISSUE THREAD

**Issue by iangilman** [domainr/domainr-search-box#23]
I was just working on a project where I wanted to start the search box off already populated with a potential domain. I put the domain in the `input` as a value, but the search box didn't pick up on it. 

One possible fix is to check to see if the input is non-empty when the search box is created and automatically do a search right away. 

Also, perhaps we want to expose an "update for new input" method on the search box to cover additional edge cases. This could be as simple as aliasing `_input` which does the right thing but isn't a terribly clear name, and with the underscore it's marked as being private.

**Comment by ydnar** [comment]
@iangilman: seems reasonable to do a search immediately if there’s a value present.

**Comment by iangilman** [comment]
Cool... shall I make it so?

**Comment by case** [comment]
Go for it.

**Comment by iangilman** [comment]
I'll go ahead and close this, since #24 has landed. If we do come up with another reason to add a manual update trigger, we can revisit.
