### ISSUE TITLE
Arrow key highlighting is hidden by "available" highlighting

### ISSUE THREAD

**Issue by iangilman** [domainr/domainr-search-box#26]
If you search for something that's available, the available results get a green background. If you mouse over them, the green darkens. If, however, you use the arrow keys to move over them, the green does not darken (even though the arrow keys do darken non-available results).

**Comment by case** [comment]
Thanks for filing this, Ian!

**Comment by iangilman** [comment]
I imagine it's a matter of adding a second selector based on `.selected` to every style based on `:hover` in https://github.com/domainr/domainr-search-box/blob/master/src/index.css
